# Site settings
title: Ilwoong's CV 
description: Ilwoong Jeong's CV
baseurl: 
url: https://ilwoong.github.io

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Ilwoong Jeong
  title: Senior Researcher
  address: Daejeon, Republic of Korea
  email: ilwoong.jeong@gmail.com
  link: https://woong.pe.kr
  weibo:
  github: ilwoong
  linkedin: ilwoong
  workHistory:
    - work1:
      company: Samsung Electronics
      location: Daejeon, Republic of Korea
      title: Java Developer
      started: 2015
      duration: (2015 - Present)      
    - work2:
      company: The Affiliated Institute of ETRI
      location: Suwon, Republic of Korea
      title: Senior Engineer
      started: 2011
      duration: (2011 - 2014)
  educationHistory:
    - education1:
      organization: KAIST
      location: Daejeon, Republic of Korea
      degree: Ph.D.
      major: Computer Science
      started: 2004
      duration: (2004 - 2010)
    - education2:
      organization: KAIST
      location: Daejeon, Republic of Korea
      degree: Master
      major: Computer Science
      started: 2002
      duration: (2002 - 2004)
    - education3:
      organization: Ajou University
      location: Suwon, Republic of Korea
      degree: Bachelor
      major: Information and Computer Science
      started: 2002
      duration: (2002 - 2004)
  languages:
    - language1:
      name: Korean
      proficiency: Native
    - language2:
      name: English
      proficiency: Limit
  programmingSkills:
    - skill1:
      name: C
      percentage: 100%
    - skill2:
      name: C++
      percentage: 90%
    - skill3:
      name: Java
      percentage: 100%
    - skill4:
      name: WPF
      percentage: 50%